### PR TITLE
fix: Explicit grouping for regex in OpenAPI type name normalization

### PR DESCRIPTION
**Pull request by provinzkraut**
### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description

#2475 introduced a new regex with a potential for "catastrophic backtracking" ([SonarCloud analysis](https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&types=BUG&id=litestar-org_litestar&open=AYvgiwx-edsUYnEP43pU)). This is fixed by introducing explicit grouping.

### CODE REVIEW

**Review by peterschutt — APPROVED** [review]

**Comment by peterschutt** [comment]
This didn't fix it unfortunately - it is still reporting the same error with the 2nd group added.. maybe it wants groups within the first group..

https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=litestar-org_litestar&open=AYvgiwx-edsUYnEP43pU

and 

https://sonarcloud.io/project/security_hotspots?id=litestar-org_litestar

However, the grouping reliability issue seems unrelated to the "catastrophic backtracking" security issue, where the latter would only be an issue if the pattern was fed from user-input.

**Comment by provinzkraut** [comment]
> This didn't fix it unfortunately - it is still reporting the same error with the 2nd group added.. 

Weird that it didn’t report this on the PR itself though? Is it just me or does the reporting in general feel a bit unreliable recently if it’s not running on `main`?

**Comment by peterschutt** [comment]
> > This didn't fix it unfortunately - it is still reporting the same error with the 2nd group added.. 
> 
> 
> 
> Weird that it didn’t report this on the PR itself though? Is it just me or does the reporting in general feel a bit unreliable recently if it’s not running on `main`?

Yeh - I noticed the same thing.

It's a shame we can't have sonar run on forks too so we can try to catch these things before we merge.. code coverage reporting is a big issue with this.

**Comment by provinzkraut** [comment]
> It's a shame we can't have sonar run on forks too so we can try to catch these things before we merge.. code coverage reporting is a big issue with this.

The code coverage is really annoying too. I feel like we must be doing something wrong here, since the usefulness is greatly reduced with the functionality as it is now.

**Comment by peterschutt** [comment]
Still a feature request: https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request

With a workaround: https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/30

We should be able to easily report coverage ourselves using https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

**Pull request merged**
