### PR TITLE
refactor: removed duplicated type hints

### PR DESCRIPTION
**Pull request by rosstitmarsh**
Removes unnecessarily repeated Nones in type unions introduced in 619cafb.

### CODE REVIEW

**Comment by cofin** [comment]
@all-contributors, add @rosstitmarsh for code

**Review by cofin — APPROVED** [review]
Thanks.  LGTM

**Review by guacs — APPROVED** [review]
Thanks!

**Review by guacs — COMMENTED** [review]
@rosstitmarsh could you set the target branch to main?

**Comment by provinzkraut** [comment]
@all-contributors add @rosstitmarsh for code

**Pull request merged**
