### PR TITLE
fix: use the full path for fetching openapi.json

### LINKED ISSUE #3047: Bug: RapiDoc and Stoplight Elements fail when used as root schema
### Description

Setting `root_schema_site="rapidoc"` or `root_schema_site="elements"` in the `OpenAPIConfig` results in an error when visiting `/schema`. Both `/schema/rapidoc` and `/schema/elements` work as expected.

The issue appears to be related to the fact that both RapiDoc and StopLight elements [are configured with `spec-url`](https://github.com/litestar-org/litestar/blob/747fb90772721e7867f2e1ff2da6636f8442a6fb/litestar/openapi/controller.py#L494) whereas Swagger UI and Redoc HTML has the OpenAPI JSON inlined via a call to `OpenAPIController._get_schema_as_json`.

### URL to code causing the issue

_No response_

### MCVE

```python
from litestar import Litestar, get
from litestar.openapi import OpenAPIConfig


@get("/")
async def hello_world() -> str:
    return "Hello world!"


app = Litestar(
    route_handlers=[hello_world],
    openapi_config=OpenAPIConfig(
        title="Test app", version="0.0.1", root_schema_site="rapidoc"
    ),
)
```

### Steps to reproduce

```bash
1. Run app with `litestar run`
2. Visit `localhost:8000/schema` in your browser.
```

### Screenshots

_No response_

### Logs

_No response_

### Litestar Version

2.5.0

### Platform

- [X] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

### PR DESCRIPTION
**Pull request by vkcku**
## Description

- This specifies the `spec-url` and `apiDescriptionUrl` of Rapidoc, and Stoplight Elements as absolute paths relative to the root of the site. This ensures that both of the send the request for the JSON of the OpenAPI schema to the right endpoint.

## Closes

Fixes #3047.

### CODE REVIEW

**Review by Alc-Alc — APPROVED** [review]

**Comment by JacobCoffee** [comment]
Can we hold off on this this initial change was due to it breaking on my end and i'd just like to test on work apps

**Comment by guacs** [comment]
> Can we hold off on merging this - the initial change was due to it breaking on my end and i'd just like to test on work apps

Initial change as in the use of `openapi.json` instead of the full path?

**Review by guacs — COMMENTED** [review]
Wait until tested.

EDIT: @JacobCoffee can you add a review comment so that no one accidentally merges this? Me adding it doesn't prevent this PR from being merged :/

**Comment by Alc-Alc** [comment]
> Wait until tested.
> 
> EDIT: @JacobCoffee can you add a review comment so that no one accidentally merges this? Me adding it doesn't prevent this PR from being merged :/

Make it draft?

**Comment by guacs** [comment]
> > Wait until tested.
> > EDIT: @JacobCoffee can you add a review comment so that no one accidentally merges this? Me adding it doesn't prevent this PR from being merged :/
> 
> Make it draft?

 That's genius.

**Review by JacobCoffee — APPROVED** [review]

**Pull request merged**
