### PR TITLE
docs: remove references to `SQLAlchemyAsyncConfig.create_engine`

### LINKED ISSUE #2374: Docs: errors in the SQLAlchemy Repository Tutorial
### Summary

Running the examples in the SQLAlchemy Repository Tutorial give the following error:

```
    |   File "toto.py", line 144, in on_startup
    |     async with sqlalchemy_config.create_engine().begin() as conn:
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | AttributeError: 'SQLAlchemyAsyncConfig' object has no attribute 'create_engine'
```

I suspect the API has changed.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2374">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2374/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by lsanpablo**
### Pull Request Checklist

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

### Description
[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"

- Remove references to `SQLAlchemyAsyncConfig.create_engine` from docs; use `SQLAlchemyAsyncConfig.get_engine` in examples instead.

### Close Issue(s)
[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

- Closes #2374

### CODE REVIEW

**Comment by lsanpablo** [comment]
According to the [advanced-alchemy docs](https://docs.advanced-alchemy.jolt.rs/latest/reference/config/common.html#advanced_alchemy.config.common.GenericSQLAlchemyConfig.get_engine:~:text=Return%20an%20engine.%20If%20none%20exists%20yet%2C%20create%20one.), `get_engine` seems like the only way to get what we want in those examples.

**Comment by peterschutt** [comment]
`create_engine()` was part of the interface in the 2.0 release, so really should still exist.

It existed in the commit prior to the `advanced-alchemy` commit:

https://github.com/litestar-org/litestar/blob/a463aab9eec73266e10db71a83d3ede95e1832c1/litestar/contrib/sqlalchemy/plugins/init/config/common.py#L174-L195

**Comment by lsanpablo** [comment]
It seems like the best thing to do is to add a deprecated `create_engine` function which just calls `get_engine` and leave the docs as they are in the PR. Correct?

**Comment by cofin** [comment]
> I agree, `create_engine` should still be part of the interface. It seems like the best thing to do is to add a deprecated `create_engine` method which just calls `get_engine` and leave the docs as they are in the PR. Correct?

Yes, I think this is correct.  This means we should probably do this over on the `advanced_alchemy` side.

**Comment by guacs** [comment]
> > I agree, `create_engine` should still be part of the interface. It seems like the best thing to do is to add a deprecated `create_engine` method which just calls `get_engine` and leave the docs as they are in the PR. Correct?
> 
> Yes, I think this is correct. This means we should probably do this over on the `advanced_alchemy` side.

Wouldn't it be better to just subclass the config and add that method in `litestar` till v3?

**Comment by provinzkraut** [comment]
> Wouldn't it be better to just subclass the config and add that method in `litestar` till v3?

Good point. We re-export things anyway from Litestar, so we might as well just do that.

**Review by peterschutt — APPROVED** [review]

**Pull request merged**
