### PR TITLE
feat: Ensures deterministic ordering of handlers

### PR DESCRIPTION
**Pull request by gsakkis**
Currently the order of controller handlers (e.g. as listed in the generated OpenAPI schema) is not only random but unstable between different runs unless [PYTHONHASHSEED](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED) is fixed (which is typically not).

This PR ensures deterministic (even if somewhat arbitrary) order.

Potential future feature: Make handler ordering configurable by the user.

### CODE REVIEW

**Comment by provinzkraut** [comment]
@gsakkis can you retarget this to the `v2.1` branch?

**Comment by gsakkis** [comment]
@provinzkraut I can but why? This is (admittedly a small but annoying) bug, why defer the fix to 2.1?

**Comment by provinzkraut** [comment]
I would argue that this is more of a feature than a bug fix. Everything is working as expected, it's just that the behaviour isn't desirable.

Unless I'm mistaken and this is a regression / does not work as expected?

**Comment by Goldziher** [comment]
> I would argue that this is more of a feature than a bug fix. Everything is working as expected, it's just that the behaviour isn't desirable.
> 
> Unless I'm mistaken and this is a regression / does not work as expected?

I wouldn't consider this a feature tbh. It's a change in implementation from something that can be considered a bug. I don't think if needs to wait for a minor version since it can't break anything.

**Comment by Goldziher** [comment]
@gsakkis also please reformat the PR title to follow conventional commits

**Pull request merged**
