### PR TITLE
fix: discrepency in attrs, msgspec and pydantic for multi-part forms

### LINKED ISSUE #2278: Bug: forms validation discrepency between underlying object and form type
### Description

Given this little app that basically enables in a browser to post a form to 6 different routes:  atrts/msgspec/pydantic times url-encoded/multi-part version, I have isues to understand why the multi-part pydantic vs attrs/msgspec different behaviour. 

I would expect a 201 on all and get a 400 on multi-part msgspec and attrs (see logs), is that intended ?

Input I pass is purposedely 1 and 1 for name and amount and the same for all POST logs below.

### URL to code causing the issue

_No response_

### MCVE

```python
from typing import Annotated

import msgspec
from attr import define, field
from attr.validators import ge, instance_of, lt
from jinja2 import Environment, DictLoader
from pydantic import BaseModel, ConfigDict, Field

from litestar import Litestar, Request, post, get
from litestar.contrib.jinja import JinjaTemplateEngine
from litestar.enums import RequestEncodingType
from litestar.params import Body
from litestar.response import Template
from litestar.template import TemplateConfig

MAX_INT_POSTGRES = 10


@define
class AddProductFormAttrs:
    name: str
    amount: int = field(validator=[instance_of(int), ge(1), lt(MAX_INT_POSTGRES)])


class AddProductFormPydantic(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    name: str
    amount: int = Field(ge=1, lt=MAX_INT_POSTGRES)


class AddProductFormMsgspec(msgspec.Struct):
    name: str
    amount: Annotated[int, msgspec.Meta(lt=MAX_INT_POSTGRES, ge=1)]


@get(path="/")
async def form_index() -> Template:
    return Template(template_name="form.html", context={"templates": ["attrs", "pydantic", "msgspec"]})


@post(path="/form/attrs")
async def form_attrs(
        request: Request, data: Annotated[AddProductFormAttrs, Body(media_type=RequestEncodingType.URL_ENCODED)]
) -> int:
    print(type(data.name))
    return data.amount


@post(path="/form/pydantic")
async def form_pydantic(
        request: Request, data: Annotated[AddProductFormPydantic, Body(media_type=RequestEncodingType.URL_ENCODED)]
) -> int:
    print(type(data.name))
    return data.amount


@post(path="/form/msgspec")
async def form_msgspec(
        request: Request, data: Annotated[AddProductFormMsgspec, Body(media_type=RequestEncodingType.URL_ENCODED)]
) -> int:
    print(type(data.name))
    return data.amount

@post(path="/form/multipart/attrs")
async def form_multipart_attrs(
    request: Request, data: Annotated[AddProductFormAttrs, Body(media_type=RequestEncodingType.MULTI_PART)]
) -> int:
    print(type(data.name))
    return data.amount


@post(path="/form/multipart/pydantic")
async def form_multipart_pydantic(
    request: Request, data: Annotated[AddProductFormPydantic, Body(media_type=RequestEncodingType.MULTI_PART)]
) -> int:
    print(type(data.name))
    return data.amount


@post(path="/form/multipart/msgspec")
async def form_multipart_msgspec(
        request: Request, data: Annotated[AddProductFormMsgspec, Body(media_type=RequestEncodingType.MULTI_PART)]
) -> int:
    print(type(data.name))
    return data.amount

form_html = """
<html>
<body>
{% for t in templates %}
    <div>{{ t }}
    <form action="/form/{{ t }}" method="post">
    <input type="text" name="name"/>
    <input type="number" name="amount"/>
    <button type="submit">Submit</button>
    </form>
    </div>
    <div>{{ t }} multipart
    <form action="/form/multipart//{{ t }}" method="post" enctype="multipart/form-data">
    <input type="text" name="name"/>
    <input type="number" name="amount"/>
    <button type="submit">Submit</button>
    </form>
    </div>
{% endfor %}
</body>
</html>
"""

environment = Environment(loader=DictLoader({"form.html": form_html}))
app = Litestar(route_handlers=[form_index, form_attrs, form_pydantic, form_msgspec, form_multipart_attrs, form_multipart_pydantic, form_multipart_msgspec],
               template_config=TemplateConfig(JinjaTemplateEngine.from_environment(jinja_environment=environment)),
               debug=True)
```

```
```

### Steps to reproduce

_No response_

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

```bash
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [29797]
INFO:     Started server process [29878]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:48782 - "GET / HTTP/1.1" 200 OK
<class 'str'>
INFO:     127.0.0.1:48782 - "POST /form/multipart/pydantic HTTP/1.1" 201 Created
INFO:     127.0.0.1:55766 - "GET / HTTP/1.1" 200 OK
<class 'str'>
INFO:     127.0.0.1:59238 - "POST /form/attrs HTTP/1.1" 201 Created
INFO:     127.0.0.1:56858 - "POST /form/multipart/attrs HTTP/1.1" 400 Bad Request
ERROR - 2023-09-04 14:24:31,1613157331 - litestar - middleware - exception raised on http connection to route /form/multipart/attrs

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `str`, got `int` - at `$.data.name`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 194, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 203, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST http://localhost:8000/form/multipart/attrs
Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `str`, got `int` - at `$.data.name`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 194, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 203, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST http://localhost:8000/form/multipart/attrs
<class 'str'>
INFO:     127.0.0.1:56870 - "POST /form/pydantic HTTP/1.1" 201 Created
<class 'str'>
INFO:     127.0.0.1:52932 - "POST /form/multipart/pydantic HTTP/1.1" 201 Created
<class 'str'>
INFO:     127.0.0.1:56944 - "POST /form/msgspec HTTP/1.1" 201 Created
INFO:     127.0.0.1:56944 - "POST /form/multipart/msgspec HTTP/1.1" 400 Bad Request
ERROR - 2023-09-04 14:24:57,1613183344 - litestar - middleware - exception raised on http connection to route /form/multipart/msgspec

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `str`, got `int` - at `$.data.name`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 194, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 203, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST http://localhost:8000/form/multipart/msgspec
Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `str`, got `int` - at `$.data.name`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 194, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 203, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST http://localhost:8000/form/multipart/msgspec
WARNING:  StatReload detected changes in 'te.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [29878]
INFO:     Started server process [30406]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:50626 - "GET / HTTP/1.1" 200 OK
<class 'str'>
INFO:     127.0.0.1:48508 - "POST /form/attrs HTTP/1.1" 201 Created
<class 'str'>
INFO:     127.0.0.1:48508 - "POST /form/pydantic HTTP/1.1" 201 Created
<class 'str'>
INFO:     127.0.0.1:48508 - "POST /form/msgspec HTTP/1.1" 201 Created
INFO:     127.0.0.1:35918 - "POST /form/multipart/attrs HTTP/1.1" 400 Bad Request
ERROR - 2023-09-04 14:26:37,1613283298 - litestar - middleware - exception raised on http connection to route /form/multipart/attrs

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `str`, got `int` - at `$.data.name`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 194, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 203, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST http://localhost:8000/form/multipart/attrs
Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `str`, got `int` - at `$.data.name`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 194, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 203, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST http://localhost:8000/form/multipart/attrs
<class 'str'>
INFO:     127.0.0.1:55018 - "POST /form/multipart/pydantic HTTP/1.1" 201 Created
INFO:     127.0.0.1:51360 - "POST /form/multipart/msgspec HTTP/1.1" 400 Bad Request
ERROR - 2023-09-04 14:26:58,1613303675 - litestar - middleware - exception raised on http connection to route /form/multipart/msgspec

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `str`, got `int` - at `$.data.name`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 194, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 203, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST http://localhost:8000/form/multipart/msgspec
Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `str`, got `int` - at `$.data.name`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/routes/http.py", line 194, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lotso/PycharmProjects/litestar/litestar/_signature/model.py", line 203, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST http://localhost:8000/form/multipart/msgspec
WARNING:  StatReload detected changes in 'te.py'. Reloading...
```

### Litestar Version

```
❯ litestar version
2.0.0beta4
```

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2278">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2278/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by euri10**
### Pull Request Checklist

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

- [x] New code has 100% test coverage
- [x] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [x] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

### Description
[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"

-

### Close Issue(s)
[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

- Fixes #2278

### CODE REVIEW

**Review by Goldziher — APPROVED** [review]
Great 👍

**Comment by euri10** [comment]
mmm no it breaks other tests

**Comment by provinzkraut** [comment]
@euri10 Are you still working on this?

**Comment by euri10** [comment]
well been afk a couple of days so it stalled :)

this said I'm kind of stuck in solving this, currently the PR shows only a test that fails for multi-part attrs/msgspec while pydantic is ok (test is parametrized so it is 6 tests, 3 flibraries times 2 form encoding)

the difference with url-encoded forms is that in the multi-part parsing there is already some serialization happening here:

https://github.com/litestar-org/litestar/blob/359fa32f87d5980dcbc30d567298cbbc7319cb19/litestar/_multipart.py#L158-L162

so in essence we ask here for attrs and msgspec to decode the bytes `b"1"` inside the mutli-part parsing.

while debugging I also noticed something I dont get, whatever the test for the multi-part case, the `type_decoders` are always pydantic related, I'm not sure where these are declared or instanciated though, that may be a hint.

At first I thought it was as simple as removing the try / except above and replace with `fields[field_name].append(post_data.decode(content_charset))` but while this solves this new tests, it breaks others, all have in common to have multiple items

any help appreciated

**Comment by euri10** [comment]
to summarize, the test added in this PR is sending 1 and 1 to a form that expects a str and int respectively

the answers are in this table, I would expect all should be a 201

the 400 error is `msgspec.ValidationError: Expected `str`, got `int` - at `$.data.name``  

<table>
<tr>
 <td>
 <td>attrs
 <td>msgspec
 <td>pydantic
<tr>
 <td>url-encoded
 <td>201
 <td>201
 <td>201
<tr>
 <td>multipart
 <td>400
 <td>400
 <td>201
</table>

on thing I found strange is that if I add a `print(type_decoders)` in the https://github.com/litestar-org/litestar/blob/359fa32f87d5980dcbc30d567298cbbc7319cb19/litestar/_multipart.py#L158-L162 in all cases I get 
`[(<function is_pydantic_model_class at 0x7f6687549b20>, <function _dec_pydantic at 0x7f66873393a0>), (<function _is_pydantic_uuid at 0x7f66873394e0>, <function _dec_pydantic_uuid at 0x7f6687339440>)]
`

i dont think this has an impact in this case, since we're talking about str/int issue here

the difference in both form types is due to the fact the url-encoded parser uses parse_numbers-false so when it reaches the point it wants to convert into the attrs/msgspec/pydantic model it has no issues, while in multi-part case the bytes are directly converted to int through the decode_json method, and once it reaches the same point it errors out, the reason pydantic doesn't is because of the coercion the lib operates iirc.

the thing that bothers me is the inconcistency between the 2, is that if I have a form that expects a str input, and a user enters 1, then it will validate it in url-encoded version and not in multi-part, so in multi-part case my form object needs to have str|int

**Review by provinzkraut — APPROVED** [review]

**Comment by provinzkraut** [comment]
@euri10 Can you drop the changes to `poetry.lock`? There has been an update to `time-machine` in version `2.13.0` that seems to cause one of the tests to hang. We'll need to address that in a separate PR.

**Comment by euri10** [comment]
seems like CI is back on track @provinzkraut :)
also, this was the discord conversation about it, might be interesting if someone needs to go back to this kind of issues: https://discord.com/channels/919193495116337154/1154356189669363783

**Comment by provinzkraut** [comment]
@all-contributors add @euri10 for bug

**Pull request merged**
