### PR TITLE
fix: enables `json` as valid redirect response.

### PR DESCRIPTION
**Pull request by cofin**
### Pull Request Checklist

[//]: # "Please review the [Litestar contribution guidelines](https://github.com/litestar-org/litestar/blob/main/CONTRIBUTING.rst) for this repository."

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

### Description

[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"

### Close Issue(s)

[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

### CODE REVIEW

**Comment by cofin** [comment]
I couldn't not think of a reason this wasn't enabled.  Was there a particular reason redirects response media types were limited?

**Review by JacobCoffee — APPROVED** [review]
I don't know the answer, but the changes look good.

**Comment by Goldziher** [comment]
We don't support XML de/ser atm.

**Comment by Goldziher** [comment]
I'm not familiar with media type css either

**Comment by cofin** [comment]
OK, I'll remove CSS and XML for now.  Are you both ok with us at least adding in JSON?

**Comment by Goldziher** [comment]
> OK, I'll remove CSS and XML for now.  Are you both ok with us at least adding in JSON?
> 
You can make another issue to add XML support, it's an edge case but is pretty easy

**Comment by cofin** [comment]
Closes #1884

**Comment by cofin** [comment]
@all-contributors, add @danechitoaie for bug reports

**Pull request merged**
