### PR TITLE
feat!: no implicit default for optional params

### LINKED ISSUE #2518: Enhancement: require explict default for optional parameters
This behavior is a bit undesirable IMO @litestar-org/maintainers - if a query param is `<smth> | None`, and it automatically defaults to `None` if not provided, that could cause problems. E.g.,:

```py
@get("/top-secret-government-cloud-using-litestar-route")
def armageddon_dead_man_switch(do_not_launch_nukes: Literal["thanks"] | None) -> None:
    if not do_not_launch_nukes:
        big_red_button.press()

# intern forgets to add query parameter to the query.
```
Stupid example, but YKWIM..

_Originally posted by @peterschutt in https://github.com/litestar-org/litestar/pull/2515#discussion_r1370960670_
            

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2518">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2518/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by peterschutt**
## Description

This PR changes behavior of parameters that are typed in a union with `None`. Prior behavior was to implicitly default their value to `None` if a value wasn't provided making an apparently non-optional parameter (i.e., no declared default) actually optional. Surprising behavior at best, dangerous at worst.

New behavior is to throw a client error when a parameter without a default is not provided.

## Closes

Closes #2518

### CODE REVIEW

**Comment by peterschutt** [comment]
Based on the `remove-openapi-controller` branch b/c it introduces the "What's new in 3.0" document that this adds to. Once that is merged we can rebase this onto 3.0.

**Comment by JacobCoffee** [comment]
@peterschutt TIL that if you have a branch pointed at another e.g., `branchA -> 3.0`, than have `branchB -> branchA`, when `branchA` is merged into `3.0`, `branchB` will automatically change its target.

Thats what the internet told me anyway

**Comment by peterschutt** [comment]
> @peterschutt TIL that if you have a branch pointed at another e.g., `branchA -> 3.0`, than have `branchB -> branchA`, when `branchA` is merged into `3.0`, `branchB` will automatically change its target.
> 
> Thats what the internet told me anyway

can confirm!

**Comment by peterschutt** [comment]
Superseded by #3361

**Pull request closed without merging**
