### PR TITLE
docs(htmx): add request_class to example

### LINKED ISSUE #3723: Bug: Request has no attribute 'htmx'
### Description

I'm trying out litestar with htmx and I encountered this problem while following the documentation

`AttributeError: 'Request' object has no attribute 'htmx'

### URL to code causing the issue

_No response_

### MCVE

```python
from pathlib import Path
from litestar import get, Litestar
from litestar.response import Template
from litestar.template import TemplateConfig

from litestar.contrib.jinja import JinjaTemplateEngine
from litestar.contrib.htmx.request import HTMXRequest
from litestar.contrib.htmx.response import HTMXTemplate


@get("/")
async def index() -> Template:
    return Template(template_name="pages/index.html")


@get(path="/form")
async def get_form(request: HTMXRequest) -> Template:
    htmx = request.htmx  #  if true will return HTMXDetails class object
    if htmx:
        print(htmx.current_url)

    context = {}
    return HTMXTemplate(template_name="partial.html", context=context, push_url="/form")


template_config = TemplateConfig(
    directory=Path(__file__).parent / "templates",
    engine=JinjaTemplateEngine,
)


app = Litestar(
    route_handlers=[index, get_form],
    template_config=template_config,
)


```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Simply HTMX</title>
  <link href="" rel="stylesheet">

  <script src="https://unpkg.com/htmx.org"></script>
</head>

<body>
  <button id="test-button" class="button is-primary" hx-get="/form" hx-swap="outerHTML">
    I'm new here...
  </button>
</body>

</html>
```
```


### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

_No response_

### Litestar Version

2.11.0

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

### PR DESCRIPTION
**Pull request by yujinyuz**
## Description

This just adds the request_class into the example provided in the htmx section. I was just following the example and encountered an error.

## Closes

#3723

### CODE REVIEW

**Review by JacobCoffee — CHANGES_REQUESTED** [review]
as @Alc-Alc mentioned

**Comment by yujinyuz** [comment]
@JacobCoffee @Alc-Alc 

Are you suggesting like a comment within the code that the `request_class` can be added or should I put it somewhere else within the htmx docs?

**Comment by Alc-Alc** [comment]
> @JacobCoffee @Alc-Alc
> 
> Are you suggesting like a comment within the code that the `request_class` can be added or should I put it somewhere else within the htmx docs?

Heya @yujinyuz, I am suggesting the following

```rst
A special :class:`~litestar.connection.Request` class, providing interaction with the
HTMX client. For a request to be considered an :class:`~litestar.contrib.htmx.request.HTMXRequest`, set ``request_class=HTMXRequest``
at a preferred layer (app / router / controller / handler).
```

over here https://github.com/litestar-org/litestar/blob/47c09ffce8e8c25a865a6703097709403a22f335/docs/usage/htmx.rst?plain=1#L6-L10

Feel free to rephrase or even rework that sentence, my suggestion is for the intent to be clear. The intent being, "add `request_class=HTMXRequest` at some layer for this to work".

@JacobCoffee FYI.

**Comment by cofin** [comment]
There are some updates coming to the HTMX documentation in this PR #3837 

Before I'd seen this, I updated the verbiage slightly to say you can add the `request_class` at any level of the app.  Feel free to re-open with changes based on those updates that include the plugin.

**Pull request closed without merging**
