### PR TITLE
fix handling of pydantic field info in openapi schema

### LINKED ISSUE #1541: Bug: OpenAPI docs parse pydantic Field()
### Description

Referencing a discussion on Discord: https://discord.com/channels/919193495116337154/1093516724864811038

It seems that the pydantic `Field()` in the model isn't parsed and generating title/description fields in the openapi.json. 

Running on docker `python:3.11-alpine`

### URL to code causing the issue

_No response_

### MCVE

```python
from starlite import Starlite, post, Controller
from pydantic import BaseModel, Field
class SomeRequestData(BaseModel):
    hostname: str = Field(title="The hostname", description="Some description")
    interface: str = Field(title="Interface", description="Interface to use")
class SomeController(Controller):
    path = "/somepath"
    @post(
        path="/test", summary="testing", tags=["Test"], description="Test description"
    )
    async def request_example(self, data: SomeRequestData) -> str:
        return "test"
app = Starlite([SomeController])
```

### Steps to reproduce

_No response_

### Screenshots

Current (as in `2.0.0a4`):
Current

Expected (as in `1.51.9`): 
Expected

### Logs

_No response_

### Litestar Version

litestar==2.0.0a4

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [X] Other (Please specify in the description above)

### PR DESCRIPTION
**Pull request by Goldziher**
### Pull Request Checklist

[//]: # "Please review the [Litestar contribution guidelines](https://github.com/litestar-org/litestar/blob/main/CONTRIBUTING.rst) for this repository."

- [x] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

### Description

[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"

### Close Issue(s)

Fixes #1541

### CODE REVIEW

**Review by JacobCoffee — COMMENTED** [review]
This worked in testing on my end for describing schema, but not fields... Still testing

**Comment by Goldziher** [comment]
> This worked in testing on my end for describing schema, but not fields... Still testing

Can you explain what you mean?

**Comment by JacobCoffee** [comment]
With the changes:
image
image

Without, on alpha 7
image


This works great.

However I would expect a description here on the query param, but maybe I have this set up wrong?
image

**Comment by Goldziher** [comment]
Can you give complete code and openapi example?

**Comment by JacobCoffee** [comment]
```py
from litestar import Litestar, post, Controller, get
from pydantic import BaseModel, Field


class CheeseData(BaseModel):
    flavor: str = Field(title="Flavor", description="Flavor of the cheese")
    age: int = Field(title="Age", description="Age of the cheese")


class CheeseController(Controller):
    path = "/somepath"

    @post(path="/post", summary="posting", tags=["Post"], description="Create the cheese")
    async def create_cheese(self, data: CheeseData) -> str:
        return "post"

    @get(path="/get", summary="getting", tags=["Get"], description="Get description")
    async def get_cheese(self, description: str = Field(..., description="Retrieve the cheese")) -> str:
        return "get"


app = Litestar([CheeseController])

```

**Comment by Goldziher** [comment]
I see. I haven't added support for this - it's the signature logic. 

I would expect you'd use our Parameter helper there instead of the pydantic field. But there is really nothing preventing us from supporting this. Except the question - should we? My thinking is no tbh. But let's c what others think. 

@litestar-org/maintainers

**Review by JacobCoffee — APPROVED** [review]
As it stands for this PRs scope, it fixed the issue with schema descriptors.

**Comment by JacobCoffee** [comment]
`Parameter` worked as a drop in replacement for `Field` so I am up in the air on whether we should do the work to support it. Maybe as a future "nice addition"? I have no strong opinions on this now that I've re-read the Parameter docs.

**Comment by JacobCoffee** [comment]
Curious on @SanderWegter's and @chris-telemetry's inputs as well

**Comment by SanderWegter** [comment]
> Curious on @SanderWegter's and @chris-telemetry's inputs as well

Just had a quick look and works exactly as expected on this branch! 👌🏻

**Pull request merged**
