### PR TITLE
feat: expose `advanced-alchemy` at `litestar.plugins.sqlalchemy`

### PR DESCRIPTION
**Pull request by cofin**
### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description

** RFC **

- This PR re-exports the official SQLAlchemy plugins at `advanced_alchemy.extension.litestar` to `litestar.plugins.sqlalchemy`

### Close Issue(s)

-

### CODE REVIEW

**Review by JacobCoffee — APPROVED** [review]

**Comment by JacobCoffee** [comment]
I think this is okay

**Comment by guacs** [comment]
A few doubts from my end:

1. Are we confident regarding the stability of the API of `advanced-alchemy`? (I know we've discussed this before, and if @cofin is confident, then I think we can confidently move forward).
2. Do we need to add any sanity tests or something to ensure things are working as expected?

**Comment by cofin** [comment]
> 2\. Do we need to add any sanity tests or something to ensure things are working as expected?

The only thing that I could think of would be creating mocks of all the expected method and signatures.  We can go down this path if everyone thinks it's best.  I was hoping to avoid this as long as possible by making sure we follow semver strictly, but maybe that's not really feasible.  Are there other options?

**Comment by cofin** [comment]
> 1. Are we confident regarding the stability of the API of `advanced-alchemy`? (I know we've discussed this before, and if @cofin is confident, then I think we can confidently move forward).

I feel like we've got a very solid set of repo and service APIs.  The rename of `get_or_create` to `get_or_upsert` has been only change to the existing method names over the last several months.  We've changed the signatures a bit from the original `*args, **kwargs`, but they've only gotten more restrictive.  Additionally, the CLI implements all of the alembic commands with their exact parameters, so this makes the CLI a bit easier to deal with.

I think we are OK re: the stability here.

**Comment by JacobCoffee** [comment]
@cofin AA 1.0.0 soon? 👀

**Comment by guacs** [comment]
> > 1. Are we confident regarding the stability of the API of `advanced-alchemy`? (I know we've discussed this before, and if @cofin is confident, then I think we can confidently move forward).
> 
> I feel like we've got a very solid set of repo and service APIs. The rename of `get_or_create` to `get_or_upsert` has been only change to the existing method names over the last several months. We've changed the signatures a bit from the original `*args, **kwargs`, but they've only gotten more restrictive. Additionally, the CLI implements all of the alembic commands with their exact parameters, so this makes the CLI a bit easier to deal with.
> 
> I think we are OK re: the stability here.

That's great! Then I think we can definitely add this and provide "first-class" support for `sqlalchemy`.

**Comment by guacs** [comment]
> > 2. Do we need to add any sanity tests or something to ensure things are working as expected?
> 
> The only thing that I could think of would be creating mocks of all the expected method and signatures. We can go down this path if everyone thinks it's best. I was hoping to avoid this as long as possible by making sure we follow semver strictly, but maybe that's not really feasible. Are there other options?

I'm not really sure either. @litestar-org/members, any ideas?

**Review by guacs — APPROVED** [review]

**Review by provinzkraut — APPROVED** [review]

**Pull request merged**
