### PR TITLE
feat: adds before_shutdown/after_startup lifespan hooks

### PR DESCRIPTION
**Pull request by cofin**
## Description

-
Closes: #3597

### CODE REVIEW

**Comment by JacobCoffee** [comment]
am I thinking of something else or did we have these before?

**Comment by provinzkraut** [comment]
@JacobCoffee you're right. #1663.

@cofin I'm not sure if this is a good solution or pattern we should support / promote.

This would effectively be the same then as adding something to the front of `on_shutdown`. 

If the goal is to provide a way to say "run this before all `on_shutdown` hooks", it would just move the problem further down the line, because then, how do you say "run this before all the other `before_shutdown` hooks"?

IMO having hooks that depend on other hooks is an anti pattern. If your hooks involve state, you should use the lifespan context manager. And if they don't involve state, then the order they're called in shouldn't matter. If the order they are called in *does* matter, combine them together in a single hook.

(same applies to the startup hooks as well)

**Comment by cofin** [comment]
> @JacobCoffee you're right, see #1663.
> 
> @cofin I'm not sure if this is a good solution or pattern we should support / promote.
> 
> This would effectively be the same then as adding something to the front of `on_shutdown`.
> 
> If the goal is to provide a way to say "run this before all `on_shutdown` hooks", it would just move the problem further down the line, because then, how do you say "run this before all the other `before_shutdown` hooks"?
> 
> IMO having hooks that depend on other hooks is an anti pattern. If your hooks involve state, you should use the lifespan context manager. And if they don't involve state, then the order they're called in shouldn't matter. If the order they are called in _does_ matter, combine them together in a single hook.
> 
> (same applies to the startup hooks as well)
> 
> If we _do_ want to support giving priorities to some hooks, then we should implement a priority configuration

The specific need was `after_startup`.  I addd in `before_shutdown` since it seemed to make logical sense at the time.  I don't think we really need the `before_shutdown`.

While implementing these changes, I remembered us having this support previously, but I don't remember exactly why we removed though.  

I do think there's a valid case for having a set of actions that can run after specific startup sequences have loaded, so maybe, we should think about a priority/ordering mechanism?

**Comment by provinzkraut** [comment]
> I do think there's a valid case for having a set of actions that can run after specific startup sequences have loaded, so maybe, we should think about a priority/ordering mechanism?

Definitely. IMO implementing priorities would be the way to go about this.

**Pull request closed without merging**
