### PR TITLE
feat: Rate Limit Config changes.

### LINKED ISSUE #1262: Enhancement: Rate Limit Config
About  `class starlite.middleware.rate_limit.RateLimitConfig`

this， `rate_limit: Tuple[Literal['second', 'minute', 'hour', 'day'], int]`

A tuple containing a time unit (second, minute, hour, day) and quantity, e.g. (“day”, 100) or (“minute”, 5)  could be changed to  [ (“day”, 100) ,(“minute”, 5),("second",1)]?

### PR DESCRIPTION
**Pull request by sidk524**
### Pull Request Checklist

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

### Description
[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"

Updated the `RateLimitConfig `class so parameter `rate_limit `now accepts a list of tuples. Also updated current instances of `RateLimitConfig` to adopt this change

### Close Issue(s)
[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

- Closes #1262

### CODE REVIEW

**Comment by provinzkraut** [comment]
Thanks for the PR!

Unfortunately, the change you suggested would be breaking, as you can see by the failing tests. I suggest you adjust it so that the config option either accepts a `Sequence[tuple[DurationUnit, int]]` or a `tuple[DurationUnit, int]`, to retain backwards compatibility.

Also, please target the `v2.1` branch, with this, since it will not be included within the next release (`2.0.0`).

**Review by provinzkraut — CHANGES_REQUESTED** [review]
Thanks for the PR!

Unfortunately, the change you suggested would be breaking, as you can see by the failing tests. I suggest you adjust it so that the config option either accepts a `Sequence[tuple[DurationUnit, int]]` or a `tuple[DurationUnit, int]`, to retain backwards compatibility.

Also, please target the `v2.1` branch, with this, since it will not be included within the next release (`2.0.0`).

**Comment by Goldziher** [comment]
@sidk524 - please fix the tests and address the review comment

**Review by Goldziher — COMMENTED** [review]
So, I don't see that this PR actually adds functionality? Please add tests that tear multiple cutoff configurations and demonstrate this works intended. Also please update the docs to reflect this.

**Pull request closed without merging**
