### PR TITLE
docs: fix images in pypi readme

### LINKED ISSUE #1705: Docs: PyPI fails to render logo
### Summary

image

This is caused most likely due to the theme matching logic

### PR DESCRIPTION
**Pull request by JacobCoffee**
### Pull Request Checklist

[//]: # "Please review the [Litestar contribution guidelines](https://github.com/litestar-org/litestar/blob/main/CONTRIBUTING.rst) for this repository."

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

### Description

[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"
Creates a new PyPI-specific `README` that allows for correct rendering of images.
Also adds project link to pypi as done in #1707

Related https://github.com/pypi/warehouse/issues/11251

### Close Issue(s)

[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"
Fixes #1705

### CODE REVIEW

**Comment by JacobCoffee** [comment]
I don't really like this solution but it's the only one that I can find that works with both platforms

**Comment by JacobCoffee** [comment]
Add add @JacobCoffee for work infra ideas maintenance business design. 
Add @provinzkraut  for design 
cc @all-contributors

**Comment by JacobCoffee** [comment]
Add @JacobCoffee for work infra ideas maintenance business design. 
Add @provinzkraut  for design 
cc @all-contributors

**Comment by JacobCoffee** [comment]
Related https://github.com/pypi/warehouse/issues/11251

**Comment by JacobCoffee** [comment]
@all-contributors please add @JacobCoffee for work infra ideas maintenance business design and add @provinzkraut  for design

**Comment by JacobCoffee** [comment]
@all-contributors please add  @provinzkraut  for design

**Review by provinzkraut — APPROVED** [review]

**Comment by provinzkraut** [comment]
Not sure if this is the best solution, since our README keeps changing, especially with the all-contributors table, and now we need to keep two of them in sync. Isn't there a better way to do this, or at least auto-generate the PyPi specific README?

**Comment by JacobCoffee** [comment]
I haven't found any other way :(

I was thinking maybe we simplify the README anyway and have lots of links to the website and documentation instead? that might alleviate the sync fears

**Comment by JacobCoffee** [comment]
I think we should find another way, but I will bear the responsibility of keeping these in sync for now for the sake of having PyPI not look like a mess

**Pull request merged**
