### PR TITLE
test: set testing client debug default to true

### LINKED ISSUE #2010: Enhancement: set debug=True in create_test_client by default
We should set debug True in the test helpers. 

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2010">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2010/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by JacobCoffee**
### Pull Request Checklist

[//]: # "Please review the [Litestar contribution guidelines](https://github.com/litestar-org/litestar/blob/main/CONTRIBUTING.rst) for this repository."

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

### Description
- Sets the testing client debug value to True by default

[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"

### Close Issue(s)

[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

Closes #2010

### CODE REVIEW

**Comment by Goldziher** [comment]
well, there are failures exposed by this - basically its trying to serialize into json an object that cannot be serialized into json - a mock object that is being raised. This needs to be investigated.

**Comment by JacobCoffee** [comment]
Would this newly revealed issue be in the Template engine, response, or somewhere else? I am having a hard time tracking it down

**Comment by provinzkraut** [comment]
@Goldziher why was this closed?

**Comment by Goldziher** [comment]
> @Goldziher why was this closed?

Because i did this. I couldnt push to this one because its a fork by @JacobCoffee. Please dont use private forks in the future.

**Pull request closed without merging**
