### PR TITLE
feat: Upgrade Swagger UI to 5.0.0 with OpenAPI 3.1 support

### PR DESCRIPTION
**Pull request by cofin**
### Pull Request Checklist

[//]: # "Please review the [Litestar contribution guidelines](https://github.com/litestar-org/litestar/blob/main/CONTRIBUTING.rst) for this repository."

- [x] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

### Description

[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"

### Close Issue(s)

[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

### CODE REVIEW

**Comment by Goldziher** [comment]
So, we also have a workaround in the controller that needs to be removed. Namely, there is a modified version of the schema

**Review by JacobCoffee — COMMENTED** [review]
Excited for their new release! 😎

**Comment by cofin** [comment]
Rolls back the changes from this PR: https://github.com/litestar-org/litestar/pull/892

**Comment by Goldziher** [comment]
@cofin this needs removing - https://github.com/litestar-org/litestar/blob/main/litestar/openapi/controller.py#L290

**Review by JacobCoffee — APPROVED** [review]

**Review by Goldziher — APPROVED** [review]

**Pull request merged**
