### PR TITLE
fix: add default encoders for `Enums` and `EnumMeta`

### PR DESCRIPTION
**Pull request by cofin**
## Description

This addresses an issue when serializing `Enums` that was reported in discord.

```shell
Process SpawnProcess-10:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/joey/server-management/app.py", line 379, in <module>
    app = Litestar(route_handlers=[...], openapi_config=OpenAPIConfig(title="API Docs", version="1.0.0"), type_decoders={EnumMeta: lambda: None})
  File "/usr/local/lib/python3.10/dist-packages/litestar/app.py", line 470, in __init__
    self.register(route_handler)
  File "/usr/local/lib/python3.10/dist-packages/litestar/app.py", line 657, in register
    route.create_handler_map()
  File "/usr/local/lib/python3.10/dist-packages/litestar/routes/http.py", line 99, in create_handler_map
    kwargs_model = self.create_handler_kwargs_model(route_handler=route_handler)
  File "/usr/local/lib/python3.10/dist-packages/litestar/routes/base.py", line 136, in create_handler_kwargs_model
    signature_model=route_handler.signature_model,
  File "/usr/local/lib/python3.10/dist-packages/litestar/handlers/base.py", line 194, in signature_model
    self._signature_model = SignatureModel.create(
  File "/usr/local/lib/python3.10/dist-packages/litestar/_signature/model.py", line 256, in create
    annotation = cls._create_annotation(
  File "/usr/local/lib/python3.10/dist-packages/litestar/_signature/model.py", line 309, in _create_annotation
    if decoder := _get_decoder_for_type(annotation, type_decoders=type_decoders):
  File "/usr/local/lib/python3.10/dist-packages/litestar/_signature/utils.py", line 55, in _get_decoder_for_type
    return next(
  File "/usr/local/lib/python3.10/dist-packages/litestar/_signature/utils.py", line 56, in <genexpr>
    (decoder for predicate, decoder in type_decoders if predicate(target_type)),
TypeError: cannot unpack non-iterable type object
```

### CODE REVIEW

**Review by peterschutt — APPROVED** [review]

**Comment by provinzkraut** [comment]
Huh? `enum.Enum` is supported out of the box by msgspec. What's going on here? 😬

**Comment by provinzkraut** [comment]
Judging from the traceback, I think there's some weirdness happening somewhere with how we're treating the `type_encoders`, because the error does *not* come from msgspec.

**Comment by peterschutt** [comment]
Hmm, yeh sorry I should have taken a closer look.

Its coming from building type annotations for signature model, so I don't think its even serialization related.. at least directly.

and right under the line where the issue is raised:

```py
            # FIXME: temporary (hopefully) hack, see: https://github.com/jcrist/msgspec/issues/497
```

So I think we should revert and get a MCVE of the original problem.

Thanks for picking this up.

**Comment by peterschutt** [comment]
I've added a PR to revert - from the traceback in OP, the error is raising out of iteration over the the values of type decoders, which are meant to be tuples of (predicate, decoder) and somehow that is receiving some scalar type that can't be unpacked.

**Comment by cofin** [comment]
I think i've copied the wrong stack trace from discord.

Here's the correct one:
```
ERROR - 2024-03-12 20:45:24,505 - litestar - config - exception raised on http connection to route /schema/swagger

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litestar/serialization/msgspec_hooks.py", line 141, in encode_json
    return msgspec.json.encode(value, enc_hook=serializer) if serializer else _msgspec_json_encoder.encode(value)
  File "/usr/local/lib/python3.10/dist-packages/litestar/serialization/msgspec_hooks.py", line 88, in default_serializer
    raise TypeError(f"Unsupported type: {type(value)!r}")
TypeError: Unsupported type: <class 'enum.EnumMeta'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litestar/middleware/exceptions/middleware.py", line 218, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
  File "/usr/local/lib/python3.10/dist-packages/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
  File "/usr/local/lib/python3.10/dist-packages/litestar/routes/http.py", line 154, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "/usr/local/lib/python3.10/dist-packages/litestar/routes/http.py", line 205, in _get_response_data
    data = route_handler.fn(**parsed_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litestar/openapi/controller.py", line 231, in swagger_ui
    return ASGIResponse(body=self.render_swagger_ui(request), media_type=MediaType.HTML)
  File "/usr/local/lib/python3.10/dist-packages/litestar/openapi/controller.py", line 411, in render_swagger_ui
    spec: {self._get_schema_as_json(request)},
  File "/usr/local/lib/python3.10/dist-packages/litestar/openapi/controller.py", line 593, in _get_schema_as_json
    json_encoded_schema = encode_json(schema, request.route_handler.default_serializer)
  File "/usr/local/lib/python3.10/dist-packages/litestar/serialization/msgspec_hooks.py", line 143, in encode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: Unsupported type: <class 'enum.EnumMeta'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litestar/serialization/msgspec_hooks.py", line 141, in encode_json
    return msgspec.json.encode(value, enc_hook=serializer) if serializer else _msgspec_json_encoder.encode(value)
  File "/usr/local/lib/python3.10/dist-packages/litestar/serialization/msgspec_hooks.py", line 88, in default_serializer
    raise TypeError(f"Unsupported type: {type(value)!r}")
TypeError: Unsupported type: <class 'enum.EnumMeta'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litestar/middleware/exceptions/middleware.py", line 218, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
  File "/usr/local/lib/python3.10/dist-packages/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
  File "/usr/local/lib/python3.10/dist-packages/litestar/routes/http.py", line 154, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "/usr/local/lib/python3.10/dist-packages/litestar/routes/http.py", line 205, in _get_response_data
    data = route_handler.fn(**parsed_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litestar/openapi/controller.py", line 231, in swagger_ui
    return ASGIResponse(body=self.render_swagger_ui(request), media_type=MediaType.HTML)
  File "/usr/local/lib/python3.10/dist-packages/litestar/openapi/controller.py", line 411, in render_swagger_ui
    spec: {self._get_schema_as_json(request)},
  File "/usr/local/lib/python3.10/dist-packages/litestar/openapi/controller.py", line 593, in _get_schema_as_json
    json_encoded_schema = encode_json(schema, request.route_handler.default_serializer)
  File "/usr/local/lib/python3.10/dist-packages/litestar/serialization/msgspec_hooks.py", line 143, in encode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: Unsupported type: <class 'enum.EnumMeta'>
```

**Pull request merged**
