### PR TITLE
RFC: Modify the `full` group to something more useful

### PR DESCRIPTION
**Pull request by cofin**
### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description

Currently, the `full` group installs everything.  I can't imagine how this would be useful for anyone other than developers.  Which, in this case, they are covered by the `dev-dependencies` groups.  

This PR proposes changes the `full` group to a more realistic set of `full` addons.

-

### Close Issue(s)

-

### CODE REVIEW

**Comment by provinzkraut** [comment]
I'm generally in favour of this, but it would be a breaking change, so we'll have to wait until v3 until we can do this.

**Comment by cofin** [comment]
@provinzkraut I think we have to do something to fix this regardless.  Piccolo pins Pydantic to v1 at the moment.

**Comment by sinisaos** [comment]
@cofin I don't know if this is useful information for you, but [Piccolo v1](https://github.com/piccolo-orm/piccolo/releases/tag/1.0.0) has migrated to Pydantic v2.

**Comment by provinzkraut** [comment]
> @cofin I don't know if this is useful information for you, but [Piccolo v1](https://github.com/piccolo-orm/piccolo/releases/tag/1.0.0) has migrated to Pydantic v2.

This is great news for us actually. We could the just fix our piccolo issue by restricting it to `>=1.0.0`

**Comment by cofin** [comment]
Should we just close this one for now?

**Comment by cofin** [comment]
Closing this for now.  I think we should revisit this as we get closer to the next major version.

**Pull request closed without merging**
