### PR TITLE
docs: update links, formatting, grammar, and remove contractions

### LINKED ISSUE #3259: bug(docs): stale reference to pydantic signature models
https://github.com/litestar-org/litestar/blob/4b7d77ea9cfd5860e1ab61a7259062c66e2465ec/docs/usage/routing/parameters.rst?plain=1#L51

I don't think it matters how this coercion occurs for the purposes of the docs - we'd just be better off noting that it does occur and leave it at that.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3259">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3259/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### LINKED ISSUE #3260: docs: remove extra test func in test client fixture example
https://github.com/litestar-org/litestar/blob/4b7d77ea9cfd5860e1ab61a7259062c66e2465ec/docs/examples/testing/test_health_check_async.py#L16-L20

From [this part](https://docs.litestar.dev/latest/usage/testing.html#test-client) of the docs. First we say:

image

Then we go on to demonstrate how its used, but we still have the test that doesn't use the fixture in the example:

image

We should probably remove that.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3260">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3260/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by JacobCoffee**
## Description

- Link more things
  - Adds `sphinx-paramlinks` to help!
  - Usage of `term` and external intersphinx links more
- Correct more spelling
- Moar consistency of what is `wrapped` vs. not
- No contractions
- Shorten line lengths
- Cleanup of the verbose calls e.g., `MyClass <litestar.path.to.MyClass>` vs `~path.to.MyClass`
- Probably some more shit I didn't think about

## Closes

- Closes #3260, 
- Fixes #3259

### CODE REVIEW

**Comment by provinzkraut** [comment]
Can I ask.. Why the removal of the contractions? :eyes:

**Comment by JacobCoffee** [comment]
@provinzkraut i felt like it might have been easier to read for non-english speakers. maybe i am wrong? but also consistency e.g., using them vs not in a bunch of places.

and i did 🙃

**Comment by JacobCoffee** [comment]
there will be some plan to split this up maybe, idk how yet..

**Comment by JacobCoffee** [comment]
I believe there are a few straggling Pydantic references for our backend things in https://github.com/litestar-org/litestar/blob/b0e32bf9c437f190367a46edd639de8fda881f3a/docs/usage/routing/parameters.rst. I am not sure the correct changes to make against them, but I imagine it should be a `Struct`?

**Comment by JacobCoffee** [comment]
This gives me the idea of maybe having a dedicated `glossary.rst` page that we can `:term:` directive against for common things we say throughtout the docs. There are quite a few things that would be nice to jump to a definition on that I am finding while reading through.

**Comment by JacobCoffee** [comment]
This can be cherry picked from until it is ready but should be reopened and pointed at `main`

**Pull request closed without merging**
