### PR TITLE
fix: skip path parameters when validating parameters for KwargsModel

### LINKED ISSUE #3197: Feature: Allow layered `Parameter` definitions for Path Parameters
### Description

`Controller.parameters` does not allow to "pre-declare" path arguments

### MCVE

```python
from __future__ import annotations

import json

from litestar import get, Controller
from litestar.app import Litestar
from litestar.params import Parameter


class UserController(Controller):
    path = "/users/{path_item:str}"
    parameters = {
        "path_item": Parameter(description="Lorem ipsum"),  # this breaks it
        "query_item": Parameter(description="Lorem ipsum"),
        "header_item": Parameter(header="header-item", description="Lorem ipsum"),
        "cookie_item": Parameter(cookie="cookie_item", description="Lorem ipsum"),
    }

    @get()
    async def get(self, path_item: str, query_item: str, header_item: str, cookie_item: str) -> str:
        return "hello"


app = Litestar(
    [UserController],
    debug=True,
)

print(json.dumps(app.openapi_schema.to_schema(), indent=4))
```

### Steps to reproduce

Above leads to:

```
Traceback (most recent call last):
  File "/home/mtvx/Projects/myproject/api/litestar_testapp.py", line 24, in <module>
    app = Litestar(
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/app.py", line 470, in __init__
    self.register(route_handler)
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/app.py", line 657, in register
    route.create_handler_map()
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/routes/http.py", line 99, in create_handler_map
    kwargs_model = self.create_handler_kwargs_model(route_handler=route_handler)
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/routes/base.py", line 135, in create_handler_kwargs_model
    return KwargsModel.create_for_signature_model(
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/_kwargs/kwargs_model.py", line 282, in create_for_signature_model
    cls._validate_raw_kwargs(
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/_kwargs/kwargs_model.py", line 466, in _validate_raw_kwargs
    raise ImproperlyConfiguredException(
litestar.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Kwarg resolution ambiguity detected for the following keys: p, a, t, h, _, i, t, e, m. Make sure to use distinct keys for your dependencies, path parameters and aliased parameters.
```

If you comment out the `path_item` from `parameters`, then it works (but "Lorem ipsum" is not set for the path item).

### Litestar Version

2.7.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3197">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3197/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by guacs**
## Description

- The path parameters were only skipped for field definitions which resulted in an error being raised if path parameters were included as part of layered parameters. This fixes that by skipping path parameters in the validation step when creating `KwargsModel.`

## Closes

Fixes #3197.

### CODE REVIEW

**Comment by peterschutt** [comment]
Note that we have had this in our docs since layered parameters were implemented (https://github.com/litestar-org/litestar/pull/261):

image

I _think_ that _maybe_ this is the kind of ambiguity that is being avoided:

```py

@get("/{some_value: int}")
def get_some_value(some_value: int) -> Whatever:...   # some_value is path parameter

@get("/something-else")
def get_something_else(some_value: int) -> WhateverElse: ...  # some_value is query parameter

app = Litestar(
    route_handlers=[handle_get_some_value, get_something_else],
    parameters={"some_value": Parameter(description="this is some value that you want")},  # should this apply to both?
)
```

**Comment by guacs** [comment]
> Note that we have had this in our docs since layered parameters were implemented (#261):
> 
> image
> 
> I _think_ that _maybe_ this is the kind of ambiguity that is being avoided:
> 
> ```python
> @get("/{some_value: int}")
> def get_some_value(some_value: int) -> Whatever:...   # some_value is path parameter
> 
> @get("/something-else")
> def get_something_else(some_value: int) -> WhateverElse: ...  # some_value is query parameter
> 
> app = Litestar(
>     route_handlers=[handle_get_some_value, get_something_else],
>     parameters={"some_value": Parameter(description="this is some value that you want")},  # should this apply to both?
> )
> ```

Aah I hadn't realized this. Yeah, there can be some ambiguity in the example you've shown though we *could* consider that as a path parameter if you don't specify `query` in `Parameter`. That being said, even if we are going to do that, that would be a feature request and it should be something we consider separately.

For now, I'm thinking the fix should be to change the error message so that it is more accurate and displays a message explaining that path parameters can't be used as layered parameters.

**Comment by tuukkamustonen** [comment]
Is there really a problem here:

```py
@get("/{some_value: int}")
def get_some_value(some_value: int) -> Whatever:...   # some_value is path parameter

@get("/something-else")
def get_something_else(some_value: int) -> WhateverElse: ...  # some_value is query parameter

app = Litestar(
    route_handlers=[handle_get_some_value, get_something_else],
    parameters={"some_value": Parameter(description="this is some value that you want")},  # should this apply to both?
)
```

Yes, it would apply to both (whichever gets read first, I guess). User's choice to use similar naming so it's intentional.

Next evolution would be to support:

```py
app = Litestar(
    ...,
    parameters={
        "path_param": Path(description="this is some value that you want")
        "query_param": Query(description="this is some value that you want")
        "any_param": Parameter(description="this is some value that you want")
    },
)
```

I guess currently that would be:

```py
app = Litestar(
    ...,
    parameters={
        "path_param": Parameter(path=..., description="this is some value that you want")
        "query_param": Parameter(query=..., description="this is some value that you want")
        "any_param": Parameter(description="this is some value that you want")
    },
)
```

**Comment by peterschutt** [comment]
> Is there really a problem here:

Well, we can either accept that the ambiguity exists and call it a feature, or disallow it. For better or worse, since layered parameters were introduced this pattern has been explicitly documented as disallowed and so the best that can happen is we develop this change as a feature, but from what I've read, there doesn't seem to be much support for doing so at this time.

> ```python
> app = Litestar(
>     ...,
>     parameters={
>         "path_param": Path(description="this is some value that you want"),
>         "query_param": Query(description="this is some value that you want"),
>         "any_param": Parameter(description="this is some value that you want"),
>     },
> )
> ```

I'd be interested in exploring along these lines to target v3. Having distinct types for the different types of parameter is more explicit (i.e., there's no domain knowledge necessary to know that `thing: Annotated[int, Query(gt=3)]` is implicitly a query parameter), and it would remove the need to double supply the name of the header/cookie when it is the same as the func param (`thing: Annotated[int, Parameter(header="thing")]`, vs `thing: Annotated[int, Header()]`).

I'll close this PR - no point fragmenting discussion between here and in #3197.

@guacs I'll cherry pick your fix for the exception message into another PR.

**Comment by tuukkamustonen** [comment]
Fair enough, expecting to see a lot of good stuff, perhaps also that `Query`/`Path`/`Cookie`/whatnot separation, in 3.0 😄

Should I open a ticket about it, or did one exist already...

**Comment by guacs** [comment]
> Fair enough, expecting to see a lot of good stuff, perhaps also that `Query`/`Path`/`Cookie`/whatnot separation, in 3.0 😄
> 
> Should I open a ticket about it, or did one exist already...

#3053 is the issue to track this.

**Pull request closed without merging**
