### PR TITLE
feat(tests): Parallelize test suite with pytest-xdist

### PR DESCRIPTION
**Pull request by provinzkraut**
Add [pytest-xdist](https://pytest-xdist.readthedocs.io) to speed up the tests.
A few tests had to be adjusted along the way to eliminate race conditions and combat lack of isolation (=

### CODE REVIEW

**Comment by provinzkraut** [comment]
I'm not yet sure whether to enable this by default. The issue is that `pytest-xdist` doesn't work well with most debuggers, which means you'd have to set either the `--pdb` flag or `-n=0` when running pytest to get the debuggers working.

Now instead, you'll have to explicitly set `-n=auto` to enable `pytest-xdist`.

I guess it depends on the individual workflows which is more convenient.
@litestar-org/maintainers @litestar-org/members please provide your input! (=

**Comment by Goldziher** [comment]
please enable it in CI, not locally.

**Review by JacobCoffee — APPROVED** [review]
pytest go brrrrrrrr

**Comment by provinzkraut** [comment]
> please enable it in CI, not locally.

Hm. I quite like having it locally, but I didn't want to force people to use it, so it left it out of the general pytest strategy and only added it to the `Makefile`. Do you guys use those?

My thinking was that this gives - with relative ease - easy access to both:

- Run `make test` to run the full speed, complete suite
- Run `pytest <whatever>` to debug things, without having to override anything

This made sense to me as I assumed you'd usually run individual parts while developing / debugging, where `pytest-xdist` would get in the way, and the whole suite *not* while debugging, where `pytest-xdist` could be useful since it cuts down the time.

If I'm in the minority here with this and it's more convenient for you guys I'm happy to change the setup though (=

**Comment by JacobCoffee** [comment]
Yeah that works, i think. I use the makefile a lot but I can use pytest by itself if i run into issues. I am not worried really about issues I run into but onboarding new contributors that may have 50 questions. but this solves it, i think

**Comment by provinzkraut** [comment]
> onboarding new contributors that may have 50 questions

I actually thought it'd make it easier, since it's somewhat of a sane default, and you won't have to add special flags / options to make stuff work!

**Comment by Goldziher** [comment]
Ok, fine for me. I dont use the make file but the IDE and i constantly use the debugger.

**Comment by provinzkraut** [comment]
> Ok, fine for me. I dont use the make file but the IDE and i constantly use the debugger.

Well then you're just like me and everything should work as expected since these runs won't use pytest-xdist (=

**Pull request merged**
