### PR TITLE
ci: only run on ready prs

### PR DESCRIPTION
**Pull request by JacobCoffee**
### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description

- only run things on ready-state PRs

### Close Issue(s)

-

### CODE REVIEW

**Comment by JacobCoffee** [comment]
ahh idk :\

**Comment by peterschutt** [comment]
What's the background context for this change?

**Comment by JacobCoffee** [comment]
@peterschutt @guacs  asked :P 

https://github.com/litestar-org/litestar/pull/2661#issuecomment-1817352148

**Comment by guacs** [comment]
> @peterschutt @guacs asked :P
> 
> [#2661 (comment)](https://github.com/litestar-org/litestar/pull/2661#issuecomment-1817352148) I was just trying to see if it was easily doable.
> 
> It looks like we would have to place, in addition to whats there now, an `if pr = not draft` on each job under jobs though.. Which would be fine.. but im not sure if anyone relies on these in draft either

Yeah, I was thinking about this. It might be better to leave it as it is currently since it won't be possible to run the tests and some people might rely on the tests running when they're contributing.

**Comment by peterschutt** [comment]
> [#2661 (comment)](https://github.com/litestar-org/litestar/pull/2661#issuecomment-1817352148)

Thanks - I'm not really a fan of this idea.

What's the issue with tests running on drafts @guacs?

One can always [put `[skip ci]` in a commit message](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/) to stop tests running for a given commit, but as far as I know there'd be no way to do the opposite of that if we make this change and want the tests to run (e.g., to see if anything has broken after merging in changes into a PR from `main` through the GH UI).

**Comment by guacs** [comment]
> > [#2661 (comment)](https://github.com/litestar-org/litestar/pull/2661#issuecomment-1817352148)
> 
> Thanks - I'm not really a fan of this idea.
> 
> What's the issue with tests running on drafts @guacs?
> 
> One can always [put `[skip ci]` in a commit message](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/) to stop tests running for a given commit, but as far as I know there'd be no way to do the opposite of that if we make this change and want the tests to run (e.g., to see if anything has broken after merging in changes into a PR from `main` through the GH UI).

No issues really. I just saw that the tests ran when merging from main in the draft PR regarding the `provide` and thought that it was a waste to run the tests and wondered whether it was possible to just disable them.

I agree with you that it's not a good idea.

**Pull request closed without merging**
