### PR TITLE
Changed all faulty links to original ones Issue number #1921

### LINKED ISSUE #1921: List to changelog in website, broken
### Summary

The link to the changelog (`https://docs.starliteproject.dev/1/release-notes/changelog.html`) in the website (`https://docs.litestar.dev/`) is broken. It results in a 404.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1921">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1921/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by RavanaBhrama**
- [x] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

### Description
This pull request is to let you know that the faulty link of "https://docs.starliteproject.dev/1/release-notes/changelog.html" is now replaced with the correct link so as to remove the error of "404 Page not found"

### Close Issue(s)

Fixes #1921

### CODE REVIEW

**Comment by provinzkraut** [comment]
Please fix the links on the `v1.51` branch within the `docs` source. The changes made within this PR would be overwritten with the next deployment.

**Comment by JacobCoffee** [comment]
@provinzkraut I didn't see this anywhere else in the code, am i going blind? 🤣 
Searching https://github.com/search?q=org%3Alitestar-org+starliteproject&type=code, and searching in the 1.51 branch returned nothing

**Comment by provinzkraut** [comment]
So, I think what's happened here is that the links are all correct in the source, and this is simply a deployment gone wrong. It seems that for some reason the build was not triggered when it should have been. I'll check this out.

**Comment by Goldziher** [comment]
> So, I think what's happened here is that the links are all correct in the source, and this is simply a deployment gone wrong. It seems that for some reason the build was not triggered when it should have been. I'll check this out.

Not really. The logic requires adjustments in multiple places. The actual plugin stuff is rather simple and small - no need for two plugins at all. 

We might refactor this in the future of course, or simply kill pydantic v1 support in our V3.

**Comment by provinzkraut** [comment]
@Goldziher I think you might have replied to the wrong issue ;)

**Comment by Goldziher** [comment]
> @Goldziher I think you might have replied to the wrong issue ;)

🤦‍♂️

**Comment by provinzkraut** [comment]
It is fixed now by the newest deployment (=

**Comment by provinzkraut** [comment]
@all-contributors add @RavanaBhrama for docs

**Pull request closed without merging**
