### PR TITLE
feat: custom dto factories for models

### PR DESCRIPTION
**Pull request by abdulhaq-e**
```python

class Bar(DeclerativeBase):
    age: int

@dataclass
class Foo:
    name: str
    bar: Bar


class FooDTO(DataclassDTO[Foo]):
    config = DTOConfig(custom_dto_factories={ 
        "bar":  SQLAlchemyDTO[Bar]
    })
```
### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description

-

### Close Issue(s)

-

### CODE REVIEW

**Comment by peterschutt** [comment]
Something to think about - what if the SQLAlchemy serialization plugin is active and someone wants to use a dataclass DTO with an embedded sqlalchemy model on the dataclass. I wonder if there's a way we could support that?

**Comment by abdulhaq-e** [comment]
> Something to think about - what if the SQLAlchemy serialization plugin is active and someone wants to use a dataclass DTO with an embedded sqlalchemy model on the dataclass. I wonder if there's a way we could support that?
> 
> ETA: And, would it be worth it?

I'm sorry can you give a quick example of such a data structure?

**Comment by peterschutt** [comment]
> > Something to think about - what if the SQLAlchemy serialization plugin is active and someone wants to use a dataclass DTO with an embedded sqlalchemy model on the dataclass. I wonder if there's a way we could support that?
> 
> > 
> 
> > ETA: And, would it be worth it?
> 
> 
> 
> I'm sorry can you give a quick example of such a data structure?

```py

class Bar(DeclerativeBase):
    age: int

@dataclass
class Foo:
    name: str
    bar: Bar


FooDTO = DataclassDTO[Foo]  # no explicit dto for sqla model

app = Litestar(..., plugins=[SQLAlchemyPlugin(...)])  # sqla plug-in so we implicitly create dto for model nested in dataclass
```

**Comment by abdulhaq-e** [comment]
Ah I see what you mean now, I'm not using the plugin so I forgot about it.

I have a feeling that what you described already works. The reason I had to implement the PR was that I had the exact same data structure, an error occurs when creating the response. The error is caused by `msgspec` not being able to encode the `SQLAlchemy` model. So with the plugin, it should just work I think.

**Comment by peterschutt** [comment]
> I have a feeling that what you described already works.

I don't think so:

```py
def test_dataclass_dto_with_sqlalchemy_plugin(create_module: Callable[[str], ModuleType]) -> None:
    module = create_module("""
from dataclasses import dataclass
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from litestar import Litestar, get
from litestar.contrib.sqlalchemy.plugins import SQLAlchemySerializationPlugin
from litestar.dto import DataclassDTO
        
class Base(DeclarativeBase): ...

class Bar(Base):
    __tablename__ = "bar"
    age: Mapped[int] = mapped_column(primary_key=True)

@dataclass
class Foo:
    name: str
    bar: Bar

FooDTO = DataclassDTO[Foo]  # no explicit dto for sqla model

@get(dto=FooDTO)
def handler() -> Foo:
    return Foo(name="foo", bar=Bar(age=1))

app = Litestar(route_handlers=[handler], plugins=[SQLAlchemySerializationPlugin()], debug=True)
"""
    )
    with TestClient(app=module.app) as client:
        response = client.get("/")
        assert response.status_code == 200
        assert response.json() == {"name": "foo", "bar": {"age": 1}}
```

```python-traceback
Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/serialization/msgspec_hooks.py", line 141, in encode_json
    return msgspec.json.encode(value, enc_hook=serializer) if serializer else _msgspec_json_encoder.encode(value)
  File "/home/peter/PycharmProjects/litestar/litestar/serialization/msgspec_hooks.py", line 88, in default_serializer
    raise TypeError(f"Unsupported type: {type(value)!r}")
TypeError: Unsupported type: <class 'nmraliteqq.Bar'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 81, in handle
    response = await self._get_response_for_request(
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 133, in _get_response_for_request
    return await self._call_handler_function(
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 157, in _call_handler_function
    response: ASGIApp = await route_handler.to_response(app=scope["app"], data=response_data, request=request)
  File "/home/peter/PycharmProjects/litestar/litestar/handlers/http_handlers/base.py", line 489, in to_response
    return await response_handler(app=app, data=data, request=request)  # type: ignore
  File "/home/peter/PycharmProjects/litestar/litestar/handlers/http_handlers/_utils.py", line 83, in handler
    return response.to_asgi_response(app=None, request=request, headers=normalize_headers(headers), cookies=cookies)
  File "/home/peter/PycharmProjects/litestar/litestar/response/base.py", line 444, in to_asgi_response
    body=self.render(self.content, media_type, get_serializer(type_encoders)),
  File "/home/peter/PycharmProjects/litestar/litestar/response/base.py", line 385, in render
    return encode_json(content, enc_hook)
  File "/home/peter/PycharmProjects/litestar/litestar/serialization/msgspec_hooks.py", line 143, in encode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: Unsupported type: <class 'nmraliteqq.Bar'>
Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/serialization/msgspec_hooks.py", line 141, in encode_json
    return msgspec.json.encode(value, enc_hook=serializer) if serializer else _msgspec_json_encoder.encode(value)
  File "/home/peter/PycharmProjects/litestar/litestar/serialization/msgspec_hooks.py", line 88, in default_serializer
    raise TypeError(f"Unsupported type: {type(value)!r}")
TypeError: Unsupported type: <class 'nmraliteqq.Bar'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/PycharmProjects/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 81, in handle
    response = await self._get_response_for_request(
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 133, in _get_response_for_request
    return await self._call_handler_function(
  File "/home/peter/PycharmProjects/litestar/litestar/routes/http.py", line 157, in _call_handler_function
    response: ASGIApp = await route_handler.to_response(app=scope["app"], data=response_data, request=request)
  File "/home/peter/PycharmProjects/litestar/litestar/handlers/http_handlers/base.py", line 489, in to_response
    return await response_handler(app=app, data=data, request=request)  # type: ignore
  File "/home/peter/PycharmProjects/litestar/litestar/handlers/http_handlers/_utils.py", line 83, in handler
    return response.to_asgi_response(app=None, request=request, headers=normalize_headers(headers), cookies=cookies)
  File "/home/peter/PycharmProjects/litestar/litestar/response/base.py", line 444, in to_asgi_response
    body=self.render(self.content, media_type, get_serializer(type_encoders)),
  File "/home/peter/PycharmProjects/litestar/litestar/response/base.py", line 385, in render
    return encode_json(content, enc_hook)
  File "/home/peter/PycharmProjects/litestar/litestar/serialization/msgspec_hooks.py", line 143, in encode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: Unsupported type: <class 'nmraliteqq.Bar'>
```

**Comment by abdulhaq-e** [comment]
I checked the code base now, I think I can see why this is happening. It seems that the serialization plugins are only used when explicit DTOs are not.

I'll give it sometime to see if that case can be handled or not.

**Comment by peterschutt** [comment]
> I checked the code base now, I think I can see why this is happening. It seems that the serialization plugins are only used when explicit DTOs are not.
> 
> 
> 
> I'll give it sometime to see if that case can be handled or not.

Yep that's right, the plug-in just creates a DTO with default config if one isn't already defined and the annotation is of a supported type.

I wouldn't let this derail your original intent with this PR though. Just might be good to think about it as we go.

**Comment by JacobCoffee** [comment]
Closing as stale

**Pull request closed without merging**
