### PR TITLE
Add repository signature namespace

### LINKED ISSUE #1586: Enhancement: `contrib.respository.on_app_init()` handler
### Summary

Callback to add to `on_app_init` that adds repository names to signature namespace.

### Basic Example

In `starlite-pg-redis-docker` I init the app with:

```py
        signature_namespace={
            "AsyncSession": AsyncSession,
            "FilterTypes": FilterTypes,
            "BeforeAfter": BeforeAfter,
            "CollectionFilter": CollectionFilter,
            "LimitOffset": LimitOffset,
            "UUID": UUID,
            "OrderBy": OrderBy,
            "SearchFilter": SearchFilter,
        },
```
These are names of things that would commonly be declared as handler or model parameter types when using the repository that are likely to get linted into an `if TYPE_CHECKING` block if using `__future__.annotations`.

E.g.,

```py
app = Litestar(..., on_app_init=[contrib.repository.on_app_init], ...)
```

### Drawbacks and Impact

It is opt in, so won't be any backward incompatible behavior.

A drawback is that it is a bit magical, but if we document it well, it might also be a good example of how to use the `signature_namespace` feature.

### Unresolved questions

_No response_

### PR DESCRIPTION
**Pull request by sonpro1296**
### Pull Request Checklist

[//]: # "Please review the [Litestar contribution guidelines](https://github.com/litestar-org/litestar/blob/main/CONTRIBUTING.rst) for this repository."

- [x] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [x] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

[//]: # "By submitting this issue, you agree to:"

[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

### Description

[//]: # "Please describe your pull request for new release changelog purposes"

### Close Issue(s)

[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"
Closes #1586

### CODE REVIEW

**Comment by JacobCoffee** [comment]
Hey @sonpro1296 - Would you be able to add docs on this to make it not so magical?

**Comment by sonpro1296** [comment]
tbh I'm not sure that I could write the docs for this feature ( it's magical indeed xD) , but more than happy to do it :)

**Review by cofin — APPROVED** [review]
LGTM

**Comment by cofin** [comment]
@all-contributors add @sonpro1296 for docs, testing, and code

**Pull request merged**
