### PR TITLE
fix: Do not send None arguments to uvicorn when reloading.

### LINKED ISSUE #2613: Bug: SSL certificate feature breaks default no-tls setups when using reload or multiple workers
### Description

the TLS certificate feature introduced in https://github.com/litestar-org/litestar/pull/2554 breaks existing installations without TLS enabled, nor TLS certificates provided.

- I did not change my setup, nor added additional arguments for TLS.

`litestar run --reload`
```
  File ".venv/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.ssl: Optional[ssl.SSLContext] = create_ssl_context(
                                         ^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/uvicorn/config.py", line 121, in create_ssl_context
    ctx.load_cert_chain(certfile, keyfile, get_password)
FileNotFoundError: [Errno 2] No such file or directory
```

I think it's a bug in uvicorn. the current implementation of `is_ssl` returns `True` if ssl_certificate and ssl_keyfile are None:
https://github.com/encode/uvicorn/blob/07c2b36455b5475ff7edfa54068ff2c0581a2be1/uvicorn/config.py#L374

`bool(self.ssl_keyfile or self.ssl_certfile)` is True, if ssl_keyfile or ssl_certificate is both None.
But the equivalent in python `bool(None or None)` yields False?

It appears that both cert parameters of `is_ssl` are type string, and not `NoneType`, wich results in True, even if no cert params are provided.

This should be filed against uvicorn, but I think this feature was not tested enough against existing setups?

### URL to code causing the issue

_No response_

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

_No response_

### Litestar Version

2.3.0

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2613">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2613/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by sykloid**
### Pull Request Checklist

- ❓  New code has 100% test coverage
- [x] Pre-Commit Checks were ran and passed
- [x] Tests were ran and passed

### Description

- Fixed a bug resulting in a `FileNotFoundError` when invoking `litestar run` with `--reload`, but without SSL `cert` or `key` files. 

### Close Issue(s)

- Fixes #2613

### CODE REVIEW

**Review by JacobCoffee — APPROVED** [review]

**Comment by JacobCoffee** [comment]
I believe `tests/unit/test_cli/test_core_commands.py` will need its tests updated

**Review by Alc-Alc — COMMENTED** [review]
Should these None cases be handled similar to how it's already handled here? https://github.com/litestar-org/litestar/blob/1f790fb29abaad89473ee105b36e21f7bc4fda92/litestar/cli/commands/core.py#L196-L210

Something like this so that it is consistent with how other optional values are passed to uvicorn?

```py
        process_args = {
            "reload": reload,
            "host": host,
            "port": port,
            "workers": workers,
            "factory": env.is_app_factory,
        }

        if certfile_path is not None:
            process_args["ssl-certfile"] = certfile_path
        if keyfile_path is not None:
            process_args["ssl-keyfile"] = keyfile_path
```

**Comment by provinzkraut** [comment]
Thanks @sykloid for your contribution! Unfortunately we need to change some things about this and get a hotfix out soon so I created #2616 which supersedes this PR. Hope you don't mind

**Comment by provinzkraut** [comment]
@all-contributors add @sykloid for bug

**Comment by provinzkraut** [comment]
@all-contributors add @sykloid for code

**Pull request closed without merging**
