### PR TITLE
fix: Validation of optional sequence in multipart data with one value 

### LINKED ISSUE #3407: Bug: cant upload one file only if type is list[UploadFile] | None
### Description

I though I had the same issue as #2939 but it's slightly different, here is a test case that fails for one file and not for 2 files:
```
@dataclass
 class OFiles:
    file_list: Optional[List[UploadFile]]


@pytest.mark.parametrize("file_count", (1, 2))
def test_upload_multiple_ofiles_in_model(file_count: int) -> None:
    @post("/")
    async def handler(data: OFiles = Body(media_type=RequestEncodingType.MULTI_PART)) -> None:
        assert len(data.file_list) == file_count

        for file in data.file_list:
            assert await file.read() == b"1"

    with create_test_client([handler]) as client:
        files_to_upload = [("file_list", b"1") for _ in range(file_count)]
        response = client.post("/", files=files_to_upload)

        assert response.status_code == HTTP_201_CREATED

```

### URL to code causing the issue

_No response_

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

_No response_

### Litestar Version

2.8.2final0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3407">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3407/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by provinzkraut**
Fix #3407.

A `Sequence[UploadFile] | None` would not pass validation when a single value was provided for a structured type, e.g. dataclass.

### CODE REVIEW

**Review by guacs — CHANGES_REQUESTED** [review]
I think the case where the annotation is directly on the handler itself also needs to be handled. I don't think there's a test for it.

```python
def handler(data: list[UploadFile] | None): ...
```

**Comment by provinzkraut** [comment]
I *think* that one is already handled but I haven't actually checked it, I assumed we were testing that already. Can't check right now as I'm on the road but I'll do once I'm back home.

**Review by Alc-Alc — APPROVED** [review]

**Comment by peterschutt** [comment]
> I think the case where the annotation is directly on the handler itself also needs to be handled. I don't think there's a test for it.
> 
> ```python
> def handler(data: list[UploadFile] | None): ...
> ```

There does seem to be an issue with this too, but its failing when there are 2 or more files provided.

**Review by peterschutt — APPROVED** [review]

**Comment by peterschutt** [comment]
> > I think the case where the annotation is directly on the handler itself also needs to be handled. I don't think there's a test for it.
> > ```python
> > def handler(data: list[UploadFile] | None): ...
> > ```
> 
> There does seem to be an issue with this too, but its failing when there are 2 or more files provided.

Created #3409 and #3410 for this

**Review by guacs — APPROVED** [review]
My comment can be ignored since another issue for that case was created. LGTM!

**Comment by provinzkraut** [comment]
> My comment can be ignored since another issue for that case was created. LGTM!

Oops. I fixed it here before that PR was created :grimacing: 
@peterschutt Should I revert?

**Comment by peterschutt** [comment]
> > My comment can be ignored since another issue for that case was created. LGTM!
> 
> Oops. I fixed it here before that PR was created 😬 @peterschutt Should I revert?

No, I'm happy for it to go though here.

**Comment by euri10** [comment]
@provinzkraut I think  we can safely ignore reportGeneralTypeIssues line 405 of multipart, merge this and close @peterschutt competing one, wdyt ?

**Comment by peterschutt** [comment]
@euri10 #3410 already closed, superseded by this. We should probably tag this as closing #3409 so it closes when it goes through.

**Comment by provinzkraut** [comment]
> @provinzkraut I think we can safely ignore reportGeneralTypeIssues line 405 of multipart, merge this and close @peterschutt competing one, wdyt ?

Don't have time rn to do this but if you want, feel free to take this on.

**Pull request merged**
