### PR TITLE
refactor: removes openapi controller and related

### PR DESCRIPTION
**Pull request by peterschutt**
## Description

This PR removes all deprecated elements of OpenAPIConfig and the OpenAPIController, removes any obsolete tests and refactors tests that were parametrized to test both OpenAPIController and the router-based approach.

This also sets Scalar as our default plugin.

### CODE REVIEW

**Comment by peterschutt** [comment]
Hey @JacobCoffee - this PR gets rid of all of the type errors coming from the removal of OpenAPIController and the other deprecated things. I can't run the tests yet though b/c of unrelated failures.

If you are working through those other errors, then I can keep merging those changes into this branch until its just openapi stuff remaining? Or, just merge this - up to you!

**Comment by JacobCoffee** [comment]
Do you think it a bad idea to merge this and if something else pops up make a new pr from this branch to continue on if I cant resolve it? not sure. i dont want to delay fixing so maybe bulk-trying-to-fix-all-the-things-at-once is a bad idea :D

**Comment by peterschutt** [comment]
> Do you think it a bad idea to merge this and if something else pops up make a new pr from this branch to continue on if I cant resolve it? not sure. i dont want to delay fixing so maybe bulk-trying-to-fix-all-the-things-at-once is a bad idea :D

I think it might be easier to break the work into logical chunks and merge them into 3.0 one at a time. That will make it easier to git blame backward through the work if we need to, and also will mean we can green-light the test suite one block at a time. Thoughts?

**Comment by JacobCoffee** [comment]
Sounds good to me, i can cherry pick off or something

**Comment by peterschutt** [comment]
Want to leave this one to me? I'll rebase on 3.0 and PR into that instead?

**Comment by provinzkraut** [comment]
> Want to leave this one to me? I'll rebase on 3.0 and PR into that instead?

I like this approach more tbh :eyes:

**Comment by peterschutt** [comment]
> > Want to leave this one to me? I'll rebase on 3.0 and PR into that instead?
> 
> 
> 
> I like this approach more tbh :eyes: 

Can you clarify? Do you mean you'd prefer a single PR into 3.0 with all the depreciations removed?

**Comment by provinzkraut** [comment]
> Can you clarify? Do you mean you'd prefer a single PR into 3.0 with all the depreciations removed?

Ah, sorry for the confusion! I just wanted to express that I liked your suggestion of doing things incrementally in smaller PRs instead of having a single big one!

**Comment by peterschutt** [comment]
Closed in favor of #3297

**Pull request closed without merging**
