### PR TITLE
fix(pydantic): `.json` and `.dict` deprecation warnings for `pydantic@2`

### LINKED ISSUE #1996: Lots of `pydantic` warnings: `.dict()` and `.json()` are deprecated
### Description

You can find lots of `DeprecationWarning` instances here: https://github.com/litestar-org/litestar/actions/runs/5578844701/jobs/10193581342

I propose to add a compat layer to call `.model_dump` and `.model_dump_json` on v2 and `.dict` and `.json` on v1, since they are both supported right now.

### URL to code causing the issue

_No response_

### MCVE

_No response_

### Steps to reproduce

_No response_

### Screenshots

_No response_

### Logs

_No response_

### Litestar Version

`main`

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

### PR DESCRIPTION
**Pull request by sobolevn**
### Pull Request Checklist

- [x] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

### Description

We now have two internal compat helpers to call `.model_dump` or `.dict`, and `.model_dump_json` or `.json` methods.

### Close Issue(s)

Closes #1996

### CODE REVIEW

**Comment by sobolevn** [comment]
This failure looks interesting: `{'conbytes': 'hello'} != {'conbytes': b'hello'}`

**Comment by sobolevn** [comment]
Oh, I see what happens :)

`assert serializer(model) == model.model_dump(mode="json") if hasattr(model, "model_dump") else model.dict()` for `pydantic@v1` always executes `assert model.dict()`

Here's the `ast` of this code:

```
Python 3.11.3 (main, Jun 21 2023, 16:11:30) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> code = """
... assert serializer(model) == model.model_dump(mode="json") if hasattr(model, "model_dump") else model.dict()
... """
>>> print(ast.dump(ast.parse(code), indent=2))
Module(
  body=[
    Assert(
      test=IfExp(
        test=Call(
          func=Name(id='hasattr', ctx=Load()),
          args=[
            Name(id='model', ctx=Load()),
            Constant(value='model_dump')],
          keywords=[]),
        body=Compare(
          left=Call(
            func=Name(id='serializer', ctx=Load()),
            args=[
              Name(id='model', ctx=Load())],
            keywords=[]),
          ops=[
            Eq()],
          comparators=[
            Call(
              func=Attribute(
                value=Name(id='model', ctx=Load()),
                attr='model_dump',
                ctx=Load()),
              args=[],
              keywords=[
                keyword(
                  arg='mode',
                  value=Constant(value='json'))])]),
        orelse=Call(
          func=Attribute(
            value=Name(id='model', ctx=Load()),
            attr='dict',
            ctx=Load()),
          args=[],
          keywords=[])))],
  type_ignores=[])
```

It should had been ``assert serializer(model) == (model.model_dump(mode="json") if hasattr(model, "model_dump") else model.dict())`

And this problem was hidden for quite some time. @Goldziher any ideas on how to fix this problem? I am not a pydantic expert :)

**Comment by Goldziher** [comment]
Oh lol

**Comment by Goldziher** [comment]
@all-contributors add @sobolevn code

**Comment by sobolevn** [comment]
Looks like `BaseModel` explicitly converts all `bytes` to `str` for some reason:

```python
pydantic.BaseModel: lambda model: {
    k: v.decode() if isinstance(v, bytes) else v for k, v in model.dict().items()
},
```

That's why this test fails:

```python
def test_serialization_of_model_instance(model: BaseModel) -> None:
    assert serializer(getattr(model, "conbytes")) == b"hello"
    assert serializer(model) == _model_dump(model)
    # Fails: {'conbytes': 'hello'} != {'conbytes': b'hello'}
```

**Comment by Goldziher** [comment]
> Looks like `BaseModel` explicitly converts all `bytes` to `str` for some reason:
> 
> ```python
> pydantic.BaseModel: lambda model: {
>     k: v.decode() if isinstance(v, bytes) else v for k, v in model.dict().items()
> },
> ```
> 
> That's why this test fails:
> 
> ```python
> def test_serialization_of_model_instance(model: BaseModel) -> None:
>     assert serializer(getattr(model, "conbytes")) == b"hello"
>     assert serializer(model) == _model_dump(model)
>     # Fails: {'conbytes': 'hello'} != {'conbytes': b'hello'}
> ```

You caught a bug. Please remove this logic.

**Comment by sobolevn** [comment]
Now `test_pydantic_json_compatibility` fails: `{'conbytes': 'hello'} != {'conbytes': 'aGVsbG8='}`

I still have no idea why :)

**Comment by Goldziher** [comment]
> Now `test_pydantic_json_compatibility` fails: `{'conbytes': 'hello'} != {'conbytes': 'aGVsbG8='}`
> 
> I still have no idea why :)

So the problem is that our serialization, which uses msgspec under the hood, does not decode bytes into strings when dumping json. Pydantic though does when dumping json. Because we do not actually use the pydantic json dumping mechanism we use the `model.dict()` method - this gives us a dict of values that we then serialize using msgspec. 

The test that is failing is ensuring that our serialization of the model.dict() result is equal to the pydantic.json() implementation. 

I can push to your PR a fix later. I'm currently AFK.

**Pull request merged**
