### PR TITLE
chore: add `pydantic` v2 as dev dependency

### PR DESCRIPTION
**Pull request by guacs**
### Pull Request Checklist

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

### Description
[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"

- update the version in `pyproject.toml`
- add `pydantic` v2 as a dev dependency without which `poetry` will install `pydantic` v1 since `piccolo` has a `<2.0` constraint

### CODE REVIEW

**Comment by provinzkraut** [comment]
It looks like this doesn't work because of the other constraints we have.

**Comment by guacs** [comment]
> It looks like this doesn't work because of the other constraints we have.

Hm..maybe `pydantic` needs to be removed first before installing v1. Let me test the CI with those changes locally.

**Review by cofin — APPROVED** [review]

**Comment by cofin** [comment]
Maybe this gets rolled into the PDM swap?

**Comment by cofin** [comment]
@guacs I think we can close this now that we've moved to PDM.  I'm pretty sure it will get installed by default now.  Thoughts?

**Comment by guacs** [comment]
> @guacs I think we can close this now that we've moved to PDM. I'm pretty sure it will get installed by default now. Thoughts?

Agreed.

**Pull request closed without merging**
