### PR TITLE
fix: use the custom request class if available when handling exceptions

### LINKED ISSUE #2399: Bug: `HTMXRequest` not passed to exception handlers, only gets access to standard `Request` object
### Description

I am trying to handle exceptions caused during HTMX requests.  But it looks like the exception handler only receives a standard `request` object, even when the routes are set to receive an `HTMXRequest`.

In the exception handler, the only flag I can find to indicate it's an HTMX request is `request._headers.get("hx-request")`.  We lose context on all other HTMX attributes in the request, which makes it difficult to troubleshoot and handle nicely.

Having access to the original HTMX request attributes can improve the flexibility of exception handling for these cases. 

### URL to code causing the issue

_No response_

### MCVE

```python
import logging
from typing import Callable

from litestar import Litestar, MediaType, Request, Response, get
from litestar.contrib.htmx.request import HTMXRequest
from litestar.contrib.htmx.response import HTMXTemplate
from litestar.contrib.jinja import JinjaTemplateEngine
from litestar.response import Template
from litestar.status_codes import HTTP_500_INTERNAL_SERVER_ERROR
from litestar.template import TemplateConfig

logger = logging.getLogger("litestar")

html = """
            <html>
                <head>
                    <script src="https://unpkg.com/htmx.org@1.9.6"></script>
                </head>
                <body>
                    <button hx-get="/htmx">Trigger HTMX</button>
                </body>
            </html>
        """


def http_500(request: Request | HTMXRequest, exc: Exception) -> Template:
    """Something broke, lets fix it"""
    request.logger.exception(f"🚨 500 ERROR: something broke on {request.url}: {exc}")

    meta = {
        "title": "500 Error... something broke bad",
        "description": "Sorry about this, we'll work on it",
    }
    return Template(
        template_name="errors/500.html.j2",
        context={
            "request": request,
            "meta": meta,
        },
    )


exception_config: dict[int | type[Exception], Callable] = {
    HTTP_500_INTERNAL_SERVER_ERROR: http_500,
}


@get("/")
async def serveHomepage(request: Request) -> Response:
    return Response(html, media_type=MediaType.HTML)


@get("/htmx")
async def serveHTMXResponse(request: HTMXRequest) -> Template:
    break_here = 1 / 0
    request.logger.info(break_here)

    return HTMXTemplate(template_name="Some HTMX Template")


app = Litestar(
    route_handlers=[serveHomepage, serveHTMXResponse],
    request_class=HTMXRequest,
    debug=True,
    exception_handlers=exception_config,
    template_config=TemplateConfig(
        directory="src/templates", engine=JinjaTemplateEngine
    ),
)
```

### Steps to reproduce

```bash
1. Load up the MRE in your favorite IDE
2. Add a breakpoint inside the `http_500` function
3. Run the app in debug mode
4. Open the homepage and click the button.  It should automatically trigger a DivisionByZero exception
5. Your IDE should break in the `http_500` function.
6. Inspect the `request` object.  If it was an `HTMXRequest`, the object type would be `litestar.contrib.htmx.request.HTMXDetails` and you would see attributes for `request.htmx`.
```

### Screenshots

_No response_

### Logs

_No response_

### Litestar Version

Litestar `2.1.1 ` and Python `3.11.5`

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2399">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2399/pledge.svg?darkmode=1">
  Fund with Polar
</picture>
</a>

### PR DESCRIPTION
**Pull request by guacs**
### Pull Request Checklist

- [x] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [x] Pre-Commit Checks were ran and passed
- [x] Tests were ran and passed

### Description

- the `request_class` on the Litestar app instance is used when handling exceptions

### Close Issue(s)

- Fixes #2399

### CODE REVIEW

**Review by cofin — APPROVED** [review]
Thanks!

LGTM

**Review by JacobCoffee — APPROVED** [review]

**Comment by guacs** [comment]
@cofin do you know why that test failed? Is it related to the PR you're working on?

**Comment by cofin** [comment]
> @cofin do you know why that test failed? Is it related to the PR you're working on?

This does look to be the same error I saw there.  However, I thought my code changes did that.  Maybe that's not the case if you are seeing it here.  It was on my list to investigate later today.

**Comment by guacs** [comment]
> It was on my list to investigate later today.

Cool. We can merge this once that's resolved.

**Comment by peterschutt** [comment]
> @cofin do you know why that test failed? Is it related to the PR you're working on?

I've noticed this occur sporadically for a while now: https://github.com/litestar-org/litestar/issues/2379

**Comment by peterschutt** [comment]
> > It was on my list to investigate later today.
> 
> Cool. We can merge this once that's resolved.

Merged, its a known flaky test and all tests passed on re-run.

**Review by peterschutt — APPROVED** [review]

**Pull request merged**
