### PR TITLE
fix: set environment variable to register CLI plugins

### PR DESCRIPTION
**Pull request by peterschutt**
### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description

- This PR addresses a bug where CLI plugins would work, but not show in the printed menu if the `LITESTAR_APP` variable was not set.

### Close Issue(s)

-

### CODE REVIEW

**Comment by peterschutt** [comment]
@cofin - do you know what is happening with those tests?

**Comment by cofin** [comment]
@peterschutt  not at the moment.  I was going to investigate this over the weekend.  This fix looks like it does what we need it to do, so it may be that the test cases need adjustment after this last addition.

**Comment by guacs** [comment]
@peterschutt this is good to merge right?

**Review by guacs — APPROVED** [review]

**Review by guacs — COMMENTED** [review]
I think it would be nice to set "LITESTAR_APP" as a constant variable.

**Review by JacobCoffee — APPROVED** [review]

**Comment by JacobCoffee** [comment]
@peterschutt  i merged this by accident when i had multiple tabs up, i thought I was on a different PR for dependabot. Unmerged and restored your branch but I think you'll need to do a new PR.. Sorry :\

**Pull request merged**
