### PR TITLE
fix(prometheus): capture templated route name for metrics

### PR DESCRIPTION
**Pull request by evstratbg**
Adding new extraction function for prometheus metrics to avoid high cardinality issue in prometheus, eg having metrics GET /v1/users/{id} is preferable over GET /v1/users/1, GET /v1/users/2,GET /v1/users/3

More info about prometheus high cardinality
https://grafana.com/blog/2022/02/15/what-are-cardinality-spikes-and-why-do-they-matter/

### CODE REVIEW

**Comment by lefuturiste** [comment]
related to #3532

**Comment by evstratbg** [comment]
@all-contributors please add @evstratbg for prometheus cardinality fix

**Comment by evstratbg** [comment]
@all-contributors please add @evstratbg  for 🚧

**Comment by evstratbg** [comment]
https://github.com/all-contributors please add @evstratbg for maintenance

**Comment by evstratbg** [comment]
@all-contributors please add @evstratbg for infra

**Review by cofin — APPROVED** [review]
@evstratbg Thanks for the work on this one.  It LGTM.

As a separate PR (you don't have to do this unless you want to), we should implement a Prometheus & OpenTelemetry plugin that will automatically configure the config and middleware at the same time.

**Comment by cofin** [comment]
@all-contributors, please add @evstratbg for code

**Pull request merged**
